language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t karlgray/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true karlgray/react-test npm test

after_success:
  - docker build -t karlgray/multi-client ./client
  - docker build -t karlgray/multi-nginx ./nginx
  - docker build -t karlgray/multi-server ./server
  - docker build -t karlgray/multi-worker ./worker